name: sports_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  google_mlkit_pose_detection: ^0.14.0
  permission_handler: ^12.0.1
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  http: ^1.1.0
  dio: ^5.3.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_analytics: ^10.7.4
  firebase_crashlytics: ^3.4.9
  firebase_remote_config: ^4.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - test_assets/
