// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADD2AGjGfsf8P0T7r9dMm74aVlURzckgs',
    appId: '1:130904067918:web:907ec1848be91e8265581f',
    messagingSenderId: '130904067918',
    projectId: 'sports-app-firebase',
    authDomain: 'sports-app-firebase.firebaseapp.com',
    storageBucket: 'sports-app-firebase.firebasestorage.app',
    measurementId: 'G-8R5WT3WH8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkGLRtb4Fh6UyO1QBaUpbuXaHAXOcU4YI',
    appId: '1:130904067918:android:aef2f65e1e0b242765581f',
    messagingSenderId: '130904067918',
    projectId: 'sports-app-firebase',
    storageBucket: 'sports-app-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLFusm7C6ezGlIJjDV4Gl7zM5cUrUxn6k',
    appId: '1:130904067918:ios:3b2031c8c67315da65581f',
    messagingSenderId: '130904067918',
    projectId: 'sports-app-firebase',
    storageBucket: 'sports-app-firebase.firebasestorage.app',
    iosBundleId: 'com.example.pushupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLFusm7C6ezGlIJjDV4Gl7zM5cUrUxn6k',
    appId: '1:130904067918:ios:3b2031c8c67315da65581f',
    messagingSenderId: '130904067918',
    projectId: 'sports-app-firebase',
    storageBucket: 'sports-app-firebase.firebasestorage.app',
    iosBundleId: 'com.example.pushupApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADD2AGjGfsf8P0T7r9dMm74aVlURzckgs',
    appId: '1:130904067918:web:77eb904bf39093df65581f',
    messagingSenderId: '130904067918',
    projectId: 'sports-app-firebase',
    authDomain: 'sports-app-firebase.firebaseapp.com',
    storageBucket: 'sports-app-firebase.firebasestorage.app',
    measurementId: 'G-PBS2JKTC3Q',
  );
}
